Vagrant.configure('2') do |config|
  config.vm.box = 'unaboxdummy'
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.provider :azure do |azure, override|
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    azure.resource_group_name = "CCGroup"
    azure.location = "uksouth"
    azure.vm_name = "azureprueba"
    azure.vm_size = "Standard_B1s"
    azure.vm_image_urn = "Canonical:UbuntuServer:16.04-LTS:16.04.201812070"
    azure.data_disks = [
       {
         name: "disco", 
         size_gb: 1
       }
    ]
    azure.dns_name = "ccazure"
    azure.tcp_endpoints = [22, 80]
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
